(function(){var z=this,O=z._,A=Array.prototype,B=Object.prototype,t=A.slice,v=B.toString,P=B.hasOwnProperty,x=Array.isArray,H=Object.keys,C=Function.prototype.bind,I=Object.create,D=function(){},b=function(a){if(a instanceof b)return a;if(!(this instanceof b))return new b(a);this._wrapped=a};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=b),exports._=b):z._=b;b.VERSION="1.8.3";var w=function(a,c,b){if(void 0===c)return a;switch(null==b?3:b){case 1:return function(b){return a.call(c,
b)};case 2:return function(b,d){return a.call(c,b,d)};case 3:return function(b,d,g){return a.call(c,b,d,g)};case 4:return function(b,d,g,h){return a.call(c,b,d,g,h)}}return function(){return a.apply(c,arguments)}},n=function(a,c,d){return null==a?b.identity:b.isFunction(a)?w(a,c,d):b.isObject(a)?b.matcher(a):b.property(a)};b.iteratee=function(a,c){return n(a,c,Infinity)};var r=function(a,c){c=null==c?a.length-1:+c;return function(){for(var b=Math.max(arguments.length-c,0),e=Array(b),f=0;f<b;f++)e[f]=
arguments[f+c];switch(c){case 0:return a.call(this,e);case 1:return a.call(this,arguments[0],e);case 2:return a.call(this,arguments[0],arguments[1],e)}b=Array(c+1);for(f=0;f<c;f++)b[f]=arguments[f];b[c]=e;return a.apply(this,b)}},J=function(a){if(!b.isObject(a))return{};if(I)return I(a);D.prototype=a;a=new D;D.prototype=null;return a},y=function(a){return function(c){return null==c?void 0:c[a]}},Q=Math.pow(2,53)-1,q=y("length"),p=function(a){a=q(a);return"number"==typeof a&&0<=a&&a<=Q};b.each=b.forEach=
function(a,c,d){c=w(c,d);var e;if(p(a))for(d=0,e=a.length;d<e;d++)c(a[d],d,a);else{var f=b.keys(a);d=0;for(e=f.length;d<e;d++)c(a[f[d]],f[d],a)}return a};b.map=b.collect=function(a,c,d){c=n(c,d);d=!p(a)&&b.keys(a);for(var e=(d||a).length,f=Array(e),g=0;g<e;g++){var h=d?d[g]:g;f[g]=c(a[h],h,a)}return f};var l=function(a){return function(c,d,e,f){d=w(d,f,4);var g=!p(c)&&b.keys(c),h=(g||c).length,k=0<a?0:h-1;3>arguments.length&&(e=c[g?g[k]:k],k+=a);for(var R=d,m=e;0<=k&&k<h;k+=a)var l=g?g[k]:k,m=R(m,
c[l],l,c);return m}};b.reduce=b.foldl=b.inject=l(1);b.reduceRight=b.foldr=l(-1);b.find=b.detect=function(a,c,d){c=p(a)?b.findIndex(a,c,d):b.findKey(a,c,d);if(void 0!==c&&-1!==c)return a[c]};b.filter=b.select=function(a,c,d){var e=[];c=n(c,d);b.each(a,function(a,b,d){c(a,b,d)&&e.push(a)});return e};b.reject=function(a,c,d){return b.filter(a,b.negate(n(c)),d)};b.every=b.all=function(a,c,d){c=n(c,d);d=!p(a)&&b.keys(a);for(var e=(d||a).length,f=0;f<e;f++){var g=d?d[f]:f;if(!c(a[g],g,a))return!1}return!0};
b.some=b.any=function(a,c,d){c=n(c,d);d=!p(a)&&b.keys(a);for(var e=(d||a).length,f=0;f<e;f++){var g=d?d[f]:f;if(c(a[g],g,a))return!0}return!1};b.contains=b.includes=b.include=function(a,c,d,e){p(a)||(a=b.values(a));if("number"!=typeof d||e)d=0;return 0<=b.indexOf(a,c,d)};b.invoke=r(function(a,c,d){var e=b.isFunction(c);return b.map(a,function(a){var b=e?c:a[c];return null==b?b:b.apply(a,d)})});b.pluck=function(a,c){return b.map(a,b.property(c))};b.where=function(a,c){return b.filter(a,b.matcher(c))};
b.findWhere=function(a,c){return b.find(a,b.matcher(c))};b.max=function(a,c,d){var e=-Infinity,f=-Infinity,g;if(null==c&&null!=a){a=p(a)?a:b.values(a);for(var h=0,k=a.length;h<k;h++)d=a[h],d>e&&(e=d)}else c=n(c,d),b.each(a,function(a,b,d){g=c(a,b,d);if(g>f||-Infinity===g&&-Infinity===e)e=a,f=g});return e};b.min=function(a,c,d){var e=Infinity,f=Infinity,g;if(null==c&&null!=a){a=p(a)?a:b.values(a);for(var h=0,k=a.length;h<k;h++)d=a[h],d<e&&(e=d)}else c=n(c,d),b.each(a,function(a,b,d){g=c(a,b,d);if(g<
f||Infinity===g&&Infinity===e)e=a,f=g});return e};b.shuffle=function(a){a=p(a)?a:b.values(a);for(var c=a.length,d=Array(c),e=0,f;e<c;e++)f=b.random(0,e),f!==e&&(d[e]=d[f]),d[f]=a[e];return d};b.sample=function(a,c,d){return null==c||d?(p(a)||(a=b.values(a)),a[b.random(a.length-1)]):b.shuffle(a).slice(0,Math.max(0,c))};b.sortBy=function(a,c,d){c=n(c,d);return b.pluck(b.map(a,function(a,b,d){return{value:a,index:b,criteria:c(a,b,d)}}).sort(function(a,c){var b=a.criteria,d=c.criteria;if(b!==d){if(b>
d||void 0===b)return 1;if(b<d||void 0===d)return-1}return a.index-c.index}),"value")};l=function(a,c){return function(d,e,f){var g=c?[[],[]]:{};e=n(e,f);b.each(d,function(c,b){var f=e(c,b,d);a(g,c,f)});return g}};b.groupBy=l(function(a,c,d){b.has(a,d)?a[d].push(c):a[d]=[c]});b.indexBy=l(function(a,c,b){a[b]=c});b.countBy=l(function(a,c,d){b.has(a,d)?a[d]++:a[d]=1});b.toArray=function(a){return a?b.isArray(a)?t.call(a):p(a)?b.map(a,b.identity):b.values(a):[]};b.size=function(a){return null==a?0:p(a)?
a.length:b.keys(a).length};b.partition=l(function(a,b,d){a[d?0:1].push(b)},!0);b.first=b.head=b.take=function(a,c,d){return null==a?void 0:null==c||d?a[0]:b.initial(a,a.length-c)};b.initial=function(a,b,d){return t.call(a,0,Math.max(0,a.length-(null==b||d?1:b)))};b.last=function(a,c,d){return null==a?void 0:null==c||d?a[a.length-1]:b.rest(a,Math.max(0,a.length-c))};b.rest=b.tail=b.drop=function(a,b,d){return t.call(a,null==b||d?1:b)};b.compact=function(a){return b.filter(a,b.identity)};var u=function(a,
c,d,e){var f=[],g=0;e=e||0;for(var h=q(a);e<h;e++){var k=a[e];if(p(k)&&(b.isArray(k)||b.isArguments(k))){c||(k=u(k,c,d));var l=0,m=k.length;for(f.length+=m;l<m;)f[g++]=k[l++]}else d||(f[g++]=k)}return f};b.flatten=function(a,b){return u(a,b,!1)};b.without=r(function(a,c){return b.difference(a,c)});b.uniq=b.unique=function(a,c,d,e){b.isBoolean(c)||(e=d,d=c,c=!1);null!=d&&(d=n(d,e));e=[];for(var f=[],g=0,h=q(a);g<h;g++){var k=a[g],l=d?d(k,g,a):k;c?(g&&f===l||e.push(k),f=l):d?b.contains(f,l)||(f.push(l),
e.push(k)):b.contains(e,k)||e.push(k)}return e};b.union=function(){return b.uniq(u(arguments,!0,!0))};b.intersection=function(a){for(var c=[],d=arguments.length,e=0,f=q(a);e<f;e++){var g=a[e];if(!b.contains(c,g)){for(var h=1;h<d&&b.contains(arguments[h],g);h++);h===d&&c.push(g)}}return c};b.difference=function(a){var c=u(arguments,!0,!0,1);return b.filter(a,function(a){return!b.contains(c,a)})};b.zip=function(){return b.unzip(arguments)};b.unzip=function(a){for(var c=a&&b.max(a,q).length||0,d=Array(c),
e=0;e<c;e++)d[e]=b.pluck(a,e);return d};b.object=function(a,b){for(var d={},e=0,f=q(a);e<f;e++)b?d[a[e]]=b[e]:d[a[e][0]]=a[e][1];return d};l=function(a){return function(b,d,e){d=n(d,e);e=q(b);for(var f=0<a?0:e-1;0<=f&&f<e;f+=a)if(d(b[f],f,b))return f;return-1}};b.findIndex=l(1);b.findLastIndex=l(-1);b.sortedIndex=function(a,b,d,e){d=n(d,e,1);b=d(b);e=0;for(var f=q(a);e<f;){var g=Math.floor((e+f)/2);d(a[g])<b?e=g+1:f=g}return e};l=function(a,c,d){return function(e,f,g){var h=0,k=q(e);if("number"==
typeof g)0<a?h=0<=g?g:Math.max(g+k,h):k=0<=g?Math.min(g+1,k):g+k+1;else if(d&&g&&k)return g=d(e,f),e[g]===f?g:-1;if(f!==f)return g=c(t.call(e,h,k),b.isNaN),0<=g?g+h:-1;for(g=0<a?h:k-1;0<=g&&g<k;g+=a)if(e[g]===f)return g;return-1}};b.indexOf=l(1,b.findIndex,b.sortedIndex);b.lastIndexOf=l(-1,b.findLastIndex);b.range=function(a,b,d){null==b&&(b=a||0,a=0);d=d||1;b=Math.max(Math.ceil((b-a)/d),0);for(var e=Array(b),f=0;f<b;f++,a+=d)e[f]=a;return e};var K=function(a,c,d,e,f){if(!(e instanceof c))return a.apply(d,
f);c=J(a.prototype);a=a.apply(c,f);return b.isObject(a)?a:c};b.bind=function(a,c){if(C&&a.bind===C)return C.apply(a,t.call(arguments,1));if(!b.isFunction(a))throw new TypeError("Bind must be called on a function");var d=t.call(arguments,2),e=r(function(b){return K(a,e,c,this,d.concat(b))});return e};b.partial=r(function(a,c){var d=b.partial.placeholder,e=function(){for(var b=0,g=c.length,h=Array(g),k=0;k<g;k++)h[k]=c[k]===d?arguments[b++]:c[k];for(;b<arguments.length;)h.push(arguments[b++]);return K(a,
e,this,this,h)};return e});b.partial.placeholder=b;b.bindAll=r(function(a,c){if(1>c.length)throw Error("bindAll must be passed function names");return b.each(c,function(c){a[c]=b.bind(a[c],a)})});b.memoize=function(a,c){var d=function(e){var f=d.cache,g=""+(c?c.apply(this,arguments):e);b.has(f,g)||(f[g]=a.apply(this,arguments));return f[g]};d.cache={};return d};b.delay=r(function(a,b,d){return setTimeout(function(){return a.apply(null,d)},b)});b.defer=b.partial(b.delay,b,1);b.throttle=function(a,
c,d){var e,f,g,h=null,k=0;d||(d={});var l=function(){k=!1===d.leading?0:b.now();h=null;g=a.apply(e,f);h||(e=f=null)};return function(){var m=b.now();k||!1!==d.leading||(k=m);var n=c-(m-k);e=this;f=arguments;0>=n||n>c?(h&&(clearTimeout(h),h=null),k=m,g=a.apply(e,f),h||(e=f=null)):h||!1===d.trailing||(h=setTimeout(l,n));return g}};b.debounce=function(a,c,d){var e,f,g,h,k,l=function(){var m=b.now()-h;m<c&&0<=m?e=setTimeout(l,c-m):(e=null,d||(k=a.apply(g,f),e||(g=f=null)))};return function(){g=this;f=
arguments;h=b.now();var m=d&&!e;e||(e=setTimeout(l,c));m&&(k=a.apply(g,f),g=f=null);return k}};b.wrap=function(a,c){return b.partial(c,a)};b.negate=function(a){return function(){return!a.apply(this,arguments)}};b.compose=function(){var a=arguments,b=a.length-1;return function(){for(var d=b,e=a[b].apply(this,arguments);d--;)e=a[d].call(this,e);return e}};b.after=function(a,b){return function(){if(1>--a)return b.apply(this,arguments)}};b.before=function(a,b){var d;return function(){0<--a&&(d=b.apply(this,
arguments));1>=a&&(b=null);return d}};b.once=b.partial(b.before,2);b.restArgs=r;var L=!{toString:null}.propertyIsEnumerable("toString"),M="valueOf isPrototypeOf toString propertyIsEnumerable hasOwnProperty toLocaleString".split(" "),N=function(a,c){var d=M.length,e=a.constructor,e=b.isFunction(e)&&e.prototype||B,f="constructor";for(b.has(a,f)&&!b.contains(c,f)&&c.push(f);d--;)f=M[d],f in a&&a[f]!==e[f]&&!b.contains(c,f)&&c.push(f)};b.keys=function(a){if(!b.isObject(a))return[];if(H)return H(a);var c=
[],d;for(d in a)b.has(a,d)&&c.push(d);L&&N(a,c);return c};b.allKeys=function(a){if(!b.isObject(a))return[];var c=[],d;for(d in a)c.push(d);L&&N(a,c);return c};b.values=function(a){for(var c=b.keys(a),d=c.length,e=Array(d),f=0;f<d;f++)e[f]=a[c[f]];return e};b.mapObject=function(a,c,d){c=n(c,d);d=b.keys(a);for(var e=d.length,f={},g=0;g<e;g++){var h=d[g];f[h]=c(a[h],h,a)}return f};b.pairs=function(a){for(var c=b.keys(a),d=c.length,e=Array(d),f=0;f<d;f++)e[f]=[c[f],a[c[f]]];return e};b.invert=function(a){for(var c=
{},d=b.keys(a),e=0,f=d.length;e<f;e++)c[a[d[e]]]=d[e];return c};b.functions=b.methods=function(a){var c=[],d;for(d in a)b.isFunction(a[d])&&c.push(d);return c.sort()};l=function(a,b){return function(d){var e=arguments.length;if(2>e||null==d)return d;for(var f=1;f<e;f++)for(var g=arguments[f],h=a(g),k=h.length,l=0;l<k;l++){var m=h[l];b&&void 0!==d[m]||(d[m]=g[m])}return d}};b.extend=l(b.allKeys);b.extendOwn=b.assign=l(b.keys);b.findKey=function(a,c,d){c=n(c,d);d=b.keys(a);for(var e,f=0,g=d.length;f<
g;f++)if(e=d[f],c(a[e],e,a))return e};b.pick=function(a,c,d){var e={},f=a,g,h;if(null==f)return e;b.isFunction(c)?(h=b.allKeys(f),g=w(c,d)):(h=u(arguments,!1,!1,1),g=function(a,b,c){return b in c},f=Object(f));for(var k=0,l=h.length;k<l;k++){var m=h[k],n=f[m];g(n,m,f)&&(e[m]=n)}return e};b.omit=function(a,c,d){if(b.isFunction(c))c=b.negate(c);else{var e=b.map(u(arguments,!1,!1,1),String);c=function(a,c){return!b.contains(e,c)}}return b.pick(a,c,d)};b.defaults=l(b.allKeys,!0);b.create=function(a,c){var d=
J(a);c&&b.extendOwn(d,c);return d};b.clone=function(a){return b.isObject(a)?b.isArray(a)?a.slice():b.extend({},a):a};b.tap=function(a,b){b(a);return a};b.isMatch=function(a,c){var d=b.keys(c),e=d.length;if(null==a)return!e;for(var f=Object(a),g=0;g<e;g++){var h=d[g];if(c[h]!==f[h]||!(h in f))return!1}return!0};var E=function(a,c,d,e){if(a===c)return 0!==a||1/a===1/c;if(null==a||null==c)return a===c;a instanceof b&&(a=a._wrapped);c instanceof b&&(c=c._wrapped);var f=v.call(a);if(f!==v.call(c))return!1;
switch(f){case "[object RegExp]":case "[object String]":return""+a===""+c;case "[object Number]":return+a!==+a?+c!==+c:0===+a?1/+a===1/c:+a===+c;case "[object Date]":case "[object Boolean]":return+a===+c}f="[object Array]"===f;if(!f){if("object"!=typeof a||"object"!=typeof c)return!1;var g=a.constructor,h=c.constructor;if(g!==h&&!(b.isFunction(g)&&g instanceof g&&b.isFunction(h)&&h instanceof h)&&"constructor"in a&&"constructor"in c)return!1}d=d||[];e=e||[];for(g=d.length;g--;)if(d[g]===a)return e[g]===
c;d.push(a);e.push(c);if(f){g=a.length;if(g!==c.length)return!1;for(;g--;)if(!E(a[g],c[g],d,e))return!1}else{f=b.keys(a);g=f.length;if(b.keys(c).length!==g)return!1;for(;g--;)if(h=f[g],!b.has(c,h)||!E(a[h],c[h],d,e))return!1}d.pop();e.pop();return!0};b.isEqual=function(a,b){return E(a,b)};b.isEmpty=function(a){return null==a?!0:p(a)&&(b.isArray(a)||b.isString(a)||b.isArguments(a))?0===a.length:0===b.keys(a).length};b.isElement=function(a){return!(!a||1!==a.nodeType)};b.isArray=x||function(a){return"[object Array]"===
v.call(a)};b.isObject=function(a){var b=typeof a;return"function"===b||"object"===b&&!!a};b.each("Arguments Function String Number Date RegExp Error".split(" "),function(a){b["is"+a]=function(b){return v.call(b)==="[object "+a+"]"}});b.isArguments(arguments)||(b.isArguments=function(a){return b.has(a,"callee")});"function"!=typeof/./&&"object"!=typeof Int8Array&&(b.isFunction=function(a){return"function"==typeof a||!1});b.isFinite=function(a){return isFinite(a)&&!isNaN(parseFloat(a))};b.isNaN=function(a){return b.isNumber(a)&&
a!==+a};b.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"===v.call(a)};b.isNull=function(a){return null===a};b.isUndefined=function(a){return void 0===a};b.has=function(a,b){return null!=a&&P.call(a,b)};b.noConflict=function(){z._=O;return this};b.identity=function(a){return a};b.constant=function(a){return function(){return a}};b.noop=function(){};b.property=y;b.propertyOf=function(a){return null==a?function(){}:function(b){return a[b]}};b.matcher=b.matches=function(a){a=b.extendOwn({},
a);return function(c){return b.isMatch(c,a)}};b.times=function(a,b,d){var e=Array(Math.max(0,a));b=w(b,d,1);for(d=0;d<a;d++)e[d]=b(d);return e};b.random=function(a,b){null==b&&(b=a,a=0);return a+Math.floor(Math.random()*(b-a+1))};b.now=Date.now||function(){return(new Date).getTime()};x={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"};y=b.invert(x);l=function(a){var c=function(b){return a[b]},d="(?:"+b.keys(a).join("|")+")",e=RegExp(d),f=RegExp(d,"g");return function(a){a=
null==a?"":""+a;return e.test(a)?a.replace(f,c):a}};b.escape=l(x);b.unescape=l(y);b.result=function(a,c,d){c=null==a?void 0:a[c];void 0===c&&(c=d);return b.isFunction(c)?c.call(a):c};var S=0;b.uniqueId=function(a){var b=++S+"";return a?a+b:b};b.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var F=/(.)^/,T={"'":"'","\\":"\\","\r":"r","\n":"n","\u2028":"u2028","\u2029":"u2029"},U=/\\|'|\r|\n|\u2028|\u2029/g,V=function(a){return"\\"+T[a]};b.template=
function(a,c,d){!c&&d&&(c=d);c=b.defaults({},c,b.templateSettings);d=RegExp([(c.escape||F).source,(c.interpolate||F).source,(c.evaluate||F).source].join("|")+"|$","g");var e=0,f="__p+='";a.replace(d,function(b,c,d,g,h){f+=a.slice(e,h).replace(U,V);e=h+b.length;c?f+="'+\n((__t=("+c+"))==null?'':_.escape(__t))+\n'":d?f+="'+\n((__t=("+d+"))==null?'':__t)+\n'":g&&(f+="';\n"+g+"\n__p+='");return b});f+="';\n";c.variable||(f="with(obj||{}){\n"+f+"}\n");f="var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};\n"+
f+"return __p;\n";try{var g=new Function(c.variable||"obj","_",f)}catch(h){throw h.source=f,h;}d=function(a){return g.call(this,a,b)};d.source="function("+(c.variable||"obj")+"){\n"+f+"}";return d};b.chain=function(a){a=b(a);a._chain=!0;return a};var G=function(a,c){return a._chain?b(c).chain():c};b.mixin=function(a){b.each(b.functions(a),function(c){var d=b[c]=a[c];b.prototype[c]=r(function(a){a.unshift(this._wrapped);return G(this,d.apply(b,a))})})};b.mixin(b);b.each("pop push reverse shift sort splice unshift".split(" "),
function(a){var c=A[a];b.prototype[a]=function(){var b=this._wrapped;c.apply(b,arguments);"shift"!==a&&"splice"!==a||0!==b.length||delete b[0];return G(this,b)}});b.each(["concat","join","slice"],function(a){var c=A[a];b.prototype[a]=function(){return G(this,c.apply(this._wrapped,arguments))}});b.prototype.value=function(){return this._wrapped};b.prototype.valueOf=b.prototype.toJSON=b.prototype.value;b.prototype.toString=function(){return""+this._wrapped};"function"===typeof define&&define.amd&&define("underscore",
[],function(){return b})}).call(this);